name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check for schema.sql changes
        id: schema-check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "schema.sql"; then
          echo "schema.sql changed"
          echo "::set-output name=changed::true"
          else
          echo "schema.sql not changed"
          echo "::set-output name=changed::false"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Pull Docker Image and Copy Data
        if: steps.schema-check.outputs.changed == 'true'
        run: |
          docker pull iamrajranjan/image_repo
          mkdir -p seed/data
          docker cp $(docker create iamrajranjan/image_repo):/docker-entrypoint-initdb.d/. seed/data/

      - name: Build Docker Image
        run: yarn seed:build

      - name: Push Changes
        run: yarn seed:push

