name: CI Workflow

on:
  push:
    branches:
      - main
    paths:
      - schema.sql

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Pull Seed Docker Image and Copy Data
        run: |
          docker pull ${{ secrets.DOCKER_SEED_DATA_IMAGE }}
          mkdir -p seed/data
          docker cp $(docker create ${{ secrets.DOCKER_SEED_DATA_IMAGE }}):/docker-entrypoint-initdb.d/. seed/data/

      - name: Build Docker Image
        run: yarn seed:build

      - name: Push Changes
        run: yarn seed:push

